### ISSUE TITLE
Hi ! I wanna be a member

### ISSUE THREAD

**Issue by Genius398** [kidcreatorsteam/www#3]
Hi!
I also have an Organisation called Educational Websites. With the same goal in mind, can I join this organisation?

**Comment by Genius398** [comment]
> Hey! Thanks for creating your first issue. You are helping!

Are you a part of this organization?

**Comment by Cool-Scratcher** [comment]
> Hi!
> I also have an Organisation called Educational Websites. With the same goal in mind, can I join this organisation?

Nope, sadly. You have to...

1. be over 9 and below 18 in age
2. know me in real life.
